<?php

return array(
    'admin'             =>
        array(
            0 =>
                array(
                    'id'           => 1,
                    'username'     => 'admin',
                    'nickname'     => 'Admin',
                    'password'     => '69069d51a48ea0bfcc76411c38cbf6ed',
                    'salt'         => 'bbec6f',
                    'avatar'       => '/assets/img/avatar.png',
                    'email'        => 'admin@admin.com',
                    'loginfailure' => 0,
                    'logintime'    => 1552874248,
                    'created_at'   => 1492186163,
                    'updated_at'   => 1552874248,
                    'token'        => '81d7b0ca-2720-4fdf-bf11-d937803f6d15',
                    'status'       => 'normal',
                ),
            1 =>
                array(
                    'id'           => 2,
                    'username'     => 'admin1',
                    'nickname'     => 'Admin',
                    'password'     => '69069d51a48ea0bfcc76411c38cbf6ed',
                    'salt'         => 'bbec6f',
                    'avatar'       => '/assets/img/avatar.png',
                    'email'        => 'admin@admin.com',
                    'loginfailure' => 0,
                    'logintime'    => 1551230698,
                    'created_at'   => 1492186163,
                    'updated_at'   => 1551230698,
                    'token'        => '00807cdb-c45d-419e-9307-2a6d64b5f18d',
                    'status'       => 'normal',
                ),
        ),
    'admin_log'         =>
        array(
            0 =>
                array(
                    'id'         => 1,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/index.php/admin/index/login',
                    'title'      => '登录',
                    'content'    => '{"__token__":"eacbd1d8283c1bacc9823b5d39d251b9","username":"admin","captcha":"QVum"}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551058216,
                ),
            1 =>
                array(
                    'id'         => 2,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/index/login.html',
                    'title'      => '登录',
                    'content'    => '{"__token__":"cfb974c1855e9f3bef2962a3cd1498fc","username":"admin","captcha":"C8FP"}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551077119,
                ),
            2 =>
                array(
                    'id'         => 3,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/general/config/check',
                    'title'      => '',
                    'content'    => '{"row":{"name":" date"}}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551088241,
                ),
            3 =>
                array(
                    'id'         => 4,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/general.config/add',
                    'title'      => '常规管理 系统配置 添加',
                    'content'    => '{"row":{"type":"date","group":"basic","name":" date","title":"\\u65e5\\u671f","value":"","content":"value1|title1value2|title2","tip":"","rule":"","extend":""}}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551088248,
                ),
            4 =>
                array(
                    'id'         => 5,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/general/config/check',
                    'title'      => '',
                    'content'    => '{"row":{"name":"string"}}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551090465,
                ),
            5 =>
                array(
                    'id'         => 6,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/general.config/add',
                    'title'      => '常规管理 系统配置 添加',
                    'content'    => '{"row":{"type":"switch","group":"basic","name":"string","title":"\\u5b57\\u7b26","value":"","content":"value1|title1value2|title2","tip":"","rule":"","extend":""}}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551090472,
                ),
            6 =>
                array(
                    'id'         => 7,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/index/login.html',
                    'title'      => '登录',
                    'content'    => '{"__token__":"27e2761baec898e34a461d31444536b0","username":"admin","captcha":"y2pp"}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551148895,
                ),
            7 =>
                array(
                    'id'         => 8,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/ajax/upload',
                    'title'      => '',
                    'content'    => '{"name":"\\u95f8\\u63a7\\u5f00\\u5173.png"}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551148911,
                ),
            8 =>
                array(
                    'id'         => 9,
                    'admin_id'   => 1,
                    'username'   => 'admin',
                    'url'        => '/admin/index/login.html',
                    'title'      => '登录',
                    'content'    => '{"__token__":"c84ee53e227337b6840324a82f73a631","username":"admin","captcha":"kht3"}',
                    'ip'         => '127.0.0.1',
                    'useragent'  => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36',
                    'created_at' => 1551230698,
                ),
        ),
    'attachment'        =>
        array(
            0 =>
                array(
                    'id'          => 1,
                    'admin_id'    => 1,
                    'user_id'     => 0,
                    'url'         => '/assets/img/qrcode.png',
                    'imagewidth'  => '150',
                    'imageheight' => '150',
                    'imagetype'   => 'png',
                    'imageframes' => 0,
                    'filesize'    => 21859,
                    'mimetype'    => 'image/png',
                    'extparam'    => '',
                    'created_at'  => 1499681848,
                    'updated_at'  => 1499681848,
                    'uploadtime'  => 1499681848,
                    'storage'     => 'local',
                    'sha1'        => '17163603d0263e4838b9387ff2cd4877e8b018f6',
                ),
            1 =>
                array(
                    'id'          => 2,
                    'admin_id'    => 1,
                    'user_id'     => 0,
                    'url'         => '/uploads/20190226/e8b0574d17afd1da2022e62d0bda8315.png',
                    'imagewidth'  => '180',
                    'imageheight' => '180',
                    'imagetype'   => 'png',
                    'imageframes' => 0,
                    'filesize'    => 6833,
                    'mimetype'    => 'image/png',
                    'extparam'    => '',
                    'created_at'  => 1551148911,
                    'updated_at'  => 1551148911,
                    'uploadtime'  => 1551148911,
                    'storage'     => 'local',
                    'sha1'        => 'f9e504e2759f4b69fdbd54b2722e905751b2f5e5',
                ),
        ),
    'auth_group'        =>
        array(
            0 =>
                array(
                    'id'         => 1,
                    'pid'        => 0,
                    'name'       => 'Admin group',
                    'rules'      => '*',
                    'created_at' => 1490883540,
                    'updated_at' => 149088354,
                    'status'     => 'normal',
                ),
            1 =>
                array(
                    'id'         => 2,
                    'pid'        => 1,
                    'name'       => 'Second group',
                    'rules'      => '13,14,16,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,40,41,42,43,44,45,46,47,48,49,50,55,56,57,58,59,60,61,62,63,64,65,1,9,10,11,7,6,8,2,4,5',
                    'created_at' => 1490883540,
                    'updated_at' => 1505465692,
                    'status'     => 'normal',
                ),
            2 =>
                array(
                    'id'         => 3,
                    'pid'        => 2,
                    'name'       => 'Third group',
                    'rules'      => '1,4,9,10,11,13,14,15,16,17,40,41,42,43,44,45,46,47,48,49,50,55,56,57,58,59,60,61,62,63,64,65,5',
                    'created_at' => 1490883540,
                    'updated_at' => 1502205322,
                    'status'     => 'normal',
                ),
            3 =>
                array(
                    'id'         => 4,
                    'pid'        => 1,
                    'name'       => 'Second group 2',
                    'rules'      => '1,4,13,14,15,16,17,55,56,57,58,59,60,61,62,63,64,65',
                    'created_at' => 1490883540,
                    'updated_at' => 1502205350,
                    'status'     => 'normal',
                ),
            4 =>
                array(
                    'id'         => 5,
                    'pid'        => 2,
                    'name'       => 'Third group 2',
                    'rules'      => '1,2,6,7,8,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34',
                    'created_at' => 1490883540,
                    'updated_at' => 1502205344,
                    'status'     => 'normal',
                ),
        ),
    'auth_group_access' =>
        array(
            0 =>
                array(
                    'uid'      => 1,
                    'group_id' => 1,
                ),
            1 =>
                array(
                    'uid'      => 2,
                    'group_id' => 2,
                ),
        ),
    'auth_rule'         =>
        array(
            0  =>
                array(
                    'id'         => 1,
                    'type'       => 'file',
                    'pid'        => 0,
                    'name'       => 'dashboard',
                    'title'      => 'Dashboard',
                    'icon'       => 'fa fa-dashboard',
                    'condition'  => '',
                    'remark'     => 'Dashboard tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 143,
                    'status'     => 'normal',
                ),
            1  =>
                array(
                    'id'         => 2,
                    'type'       => 'file',
                    'pid'        => 0,
                    'name'       => 'general',
                    'title'      => 'General',
                    'icon'       => 'fa fa-cogs',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430169,
                    'weigh'      => 137,
                    'status'     => 'normal',
                ),
            2  =>
                array(
                    'id'         => 3,
                    'type'       => 'file',
                    'pid'        => 0,
                    'name'       => 'category',
                    'title'      => 'Category',
                    'icon'       => 'fa fa-list',
                    'condition'  => '',
                    'remark'     => 'Category tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 119,
                    'status'     => 'normal',
                ),
            3  =>
                array(
                    'id'         => 4,
                    'type'       => 'file',
                    'pid'        => 0,
                    'name'       => 'addon',
                    'title'      => 'Addon',
                    'icon'       => 'fa fa-rocket',
                    'condition'  => '',
                    'remark'     => 'Addon tips',
                    'ismenu'     => 1,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            4  =>
                array(
                    'id'         => 5,
                    'type'       => 'file',
                    'pid'        => 0,
                    'name'       => 'auth',
                    'title'      => 'Auth',
                    'icon'       => 'fa fa-group',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430092,
                    'weigh'      => 99,
                    'status'     => 'normal',
                ),
            5  =>
                array(
                    'id'         => 6,
                    'type'       => 'file',
                    'pid'        => 2,
                    'name'       => 'general/config',
                    'title'      => 'Config',
                    'icon'       => 'fa fa-cog',
                    'condition'  => '',
                    'remark'     => 'Config tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430683,
                    'weigh'      => 60,
                    'status'     => 'normal',
                ),
            6  =>
                array(
                    'id'         => 7,
                    'type'       => 'file',
                    'pid'        => 2,
                    'name'       => 'general/attachment',
                    'title'      => 'Attachment',
                    'icon'       => 'fa fa-file-image-o',
                    'condition'  => '',
                    'remark'     => 'Attachment tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430699,
                    'weigh'      => 53,
                    'status'     => 'normal',
                ),
            7  =>
                array(
                    'id'         => 8,
                    'type'       => 'file',
                    'pid'        => 2,
                    'name'       => 'general/profile',
                    'title'      => 'Profile',
                    'icon'       => 'fa fa-user',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 34,
                    'status'     => 'normal',
                ),
            8  =>
                array(
                    'id'         => 9,
                    'type'       => 'file',
                    'pid'        => 5,
                    'name'       => 'auth/admin',
                    'title'      => 'Admin',
                    'icon'       => 'fa fa-user',
                    'condition'  => '',
                    'remark'     => 'Admin tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430320,
                    'weigh'      => 118,
                    'status'     => 'normal',
                ),
            9  =>
                array(
                    'id'         => 10,
                    'type'       => 'file',
                    'pid'        => 5,
                    'name'       => 'auth/adminlog',
                    'title'      => 'Admin log',
                    'icon'       => 'fa fa-list-alt',
                    'condition'  => '',
                    'remark'     => 'Admin log tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430307,
                    'weigh'      => 113,
                    'status'     => 'normal',
                ),
            10 =>
                array(
                    'id'         => 11,
                    'type'       => 'file',
                    'pid'        => 5,
                    'name'       => 'auth/group',
                    'title'      => 'Group',
                    'icon'       => 'fa fa-group',
                    'condition'  => '',
                    'remark'     => 'Group tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 109,
                    'status'     => 'normal',
                ),
            11 =>
                array(
                    'id'         => 12,
                    'type'       => 'file',
                    'pid'        => 5,
                    'name'       => 'auth/rule',
                    'title'      => 'Rule',
                    'icon'       => 'fa fa-bars',
                    'condition'  => '',
                    'remark'     => 'Rule tips',
                    'ismenu'     => 1,
                    'created_at' => 1497429920,
                    'updated_at' => 1497430581,
                    'weigh'      => 104,
                    'status'     => 'normal',
                ),
            12 =>
                array(
                    'id'         => 13,
                    'type'       => 'file',
                    'pid'        => 1,
                    'name'       => 'dashboard/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 136,
                    'status'     => 'normal',
                ),
            13 =>
                array(
                    'id'         => 14,
                    'type'       => 'file',
                    'pid'        => 1,
                    'name'       => 'dashboard/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 135,
                    'status'     => 'normal',
                ),
            14 =>
                array(
                    'id'         => 15,
                    'type'       => 'file',
                    'pid'        => 1,
                    'name'       => 'dashboard/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 133,
                    'status'     => 'normal',
                ),
            15 =>
                array(
                    'id'         => 16,
                    'type'       => 'file',
                    'pid'        => 1,
                    'name'       => 'dashboard/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 134,
                    'status'     => 'normal',
                ),
            16 =>
                array(
                    'id'         => 17,
                    'type'       => 'file',
                    'pid'        => 1,
                    'name'       => 'dashboard/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 132,
                    'status'     => 'normal',
                ),
            17 =>
                array(
                    'id'         => 18,
                    'type'       => 'file',
                    'pid'        => 6,
                    'name'       => 'general/config/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 52,
                    'status'     => 'normal',
                ),
            18 =>
                array(
                    'id'         => 19,
                    'type'       => 'file',
                    'pid'        => 6,
                    'name'       => 'general/config/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 51,
                    'status'     => 'normal',
                ),
            19 =>
                array(
                    'id'         => 20,
                    'type'       => 'file',
                    'pid'        => 6,
                    'name'       => 'general/config/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 50,
                    'status'     => 'normal',
                ),
            20 =>
                array(
                    'id'         => 21,
                    'type'       => 'file',
                    'pid'        => 6,
                    'name'       => 'general/config/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 49,
                    'status'     => 'normal',
                ),
            21 =>
                array(
                    'id'         => 22,
                    'type'       => 'file',
                    'pid'        => 6,
                    'name'       => 'general/config/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 48,
                    'status'     => 'normal',
                ),
            22 =>
                array(
                    'id'         => 23,
                    'type'       => 'file',
                    'pid'        => 7,
                    'name'       => 'general/attachment/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Attachment tips',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 59,
                    'status'     => 'normal',
                ),
            23 =>
                array(
                    'id'         => 24,
                    'type'       => 'file',
                    'pid'        => 7,
                    'name'       => 'general/attachment/select',
                    'title'      => 'Select attachment',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 58,
                    'status'     => 'normal',
                ),
            24 =>
                array(
                    'id'         => 25,
                    'type'       => 'file',
                    'pid'        => 7,
                    'name'       => 'general/attachment/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 57,
                    'status'     => 'normal',
                ),
            25 =>
                array(
                    'id'         => 26,
                    'type'       => 'file',
                    'pid'        => 7,
                    'name'       => 'general/attachment/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 56,
                    'status'     => 'normal',
                ),
            26 =>
                array(
                    'id'         => 27,
                    'type'       => 'file',
                    'pid'        => 7,
                    'name'       => 'general/attachment/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 55,
                    'status'     => 'normal',
                ),
            27 =>
                array(
                    'id'         => 28,
                    'type'       => 'file',
                    'pid'        => 7,
                    'name'       => 'general/attachment/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 54,
                    'status'     => 'normal',
                ),
            28 =>
                array(
                    'id'         => 29,
                    'type'       => 'file',
                    'pid'        => 8,
                    'name'       => 'general/profile/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 33,
                    'status'     => 'normal',
                ),
            29 =>
                array(
                    'id'         => 30,
                    'type'       => 'file',
                    'pid'        => 8,
                    'name'       => 'general/profile/update',
                    'title'      => 'Update profile',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 32,
                    'status'     => 'normal',
                ),
            30 =>
                array(
                    'id'         => 31,
                    'type'       => 'file',
                    'pid'        => 8,
                    'name'       => 'general/profile/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 31,
                    'status'     => 'normal',
                ),
            31 =>
                array(
                    'id'         => 32,
                    'type'       => 'file',
                    'pid'        => 8,
                    'name'       => 'general/profile/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 30,
                    'status'     => 'normal',
                ),
            32 =>
                array(
                    'id'         => 33,
                    'type'       => 'file',
                    'pid'        => 8,
                    'name'       => 'general/profile/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 29,
                    'status'     => 'normal',
                ),
            33 =>
                array(
                    'id'         => 34,
                    'type'       => 'file',
                    'pid'        => 8,
                    'name'       => 'general/profile/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 28,
                    'status'     => 'normal',
                ),
            34 =>
                array(
                    'id'         => 35,
                    'type'       => 'file',
                    'pid'        => 3,
                    'name'       => 'category/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Category tips',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 142,
                    'status'     => 'normal',
                ),
            35 =>
                array(
                    'id'         => 36,
                    'type'       => 'file',
                    'pid'        => 3,
                    'name'       => 'category/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 141,
                    'status'     => 'normal',
                ),
            36 =>
                array(
                    'id'         => 37,
                    'type'       => 'file',
                    'pid'        => 3,
                    'name'       => 'category/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 140,
                    'status'     => 'normal',
                ),
            37 =>
                array(
                    'id'         => 38,
                    'type'       => 'file',
                    'pid'        => 3,
                    'name'       => 'category/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 139,
                    'status'     => 'normal',
                ),
            38 =>
                array(
                    'id'         => 39,
                    'type'       => 'file',
                    'pid'        => 3,
                    'name'       => 'category/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 138,
                    'status'     => 'normal',
                ),
            39 =>
                array(
                    'id'         => 40,
                    'type'       => 'file',
                    'pid'        => 9,
                    'name'       => 'auth/admin/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Admin tips',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 117,
                    'status'     => 'normal',
                ),
            40 =>
                array(
                    'id'         => 41,
                    'type'       => 'file',
                    'pid'        => 9,
                    'name'       => 'auth/admin/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 116,
                    'status'     => 'normal',
                ),
            41 =>
                array(
                    'id'         => 42,
                    'type'       => 'file',
                    'pid'        => 9,
                    'name'       => 'auth/admin/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 115,
                    'status'     => 'normal',
                ),
            42 =>
                array(
                    'id'         => 43,
                    'type'       => 'file',
                    'pid'        => 9,
                    'name'       => 'auth/admin/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 114,
                    'status'     => 'normal',
                ),
            43 =>
                array(
                    'id'         => 44,
                    'type'       => 'file',
                    'pid'        => 10,
                    'name'       => 'auth/adminlog/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Admin log tips',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 112,
                    'status'     => 'normal',
                ),
            44 =>
                array(
                    'id'         => 45,
                    'type'       => 'file',
                    'pid'        => 10,
                    'name'       => 'auth/adminlog/detail',
                    'title'      => 'Detail',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 111,
                    'status'     => 'normal',
                ),
            45 =>
                array(
                    'id'         => 46,
                    'type'       => 'file',
                    'pid'        => 10,
                    'name'       => 'auth/adminlog/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 110,
                    'status'     => 'normal',
                ),
            46 =>
                array(
                    'id'         => 47,
                    'type'       => 'file',
                    'pid'        => 11,
                    'name'       => 'auth/group/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Group tips',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 108,
                    'status'     => 'normal',
                ),
            47 =>
                array(
                    'id'         => 48,
                    'type'       => 'file',
                    'pid'        => 11,
                    'name'       => 'auth/group/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 107,
                    'status'     => 'normal',
                ),
            48 =>
                array(
                    'id'         => 49,
                    'type'       => 'file',
                    'pid'        => 11,
                    'name'       => 'auth/group/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 106,
                    'status'     => 'normal',
                ),
            49 =>
                array(
                    'id'         => 50,
                    'type'       => 'file',
                    'pid'        => 11,
                    'name'       => 'auth/group/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 105,
                    'status'     => 'normal',
                ),
            50 =>
                array(
                    'id'         => 51,
                    'type'       => 'file',
                    'pid'        => 12,
                    'name'       => 'auth/rule/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Rule tips',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 103,
                    'status'     => 'normal',
                ),
            51 =>
                array(
                    'id'         => 52,
                    'type'       => 'file',
                    'pid'        => 12,
                    'name'       => 'auth/rule/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 102,
                    'status'     => 'normal',
                ),
            52 =>
                array(
                    'id'         => 53,
                    'type'       => 'file',
                    'pid'        => 12,
                    'name'       => 'auth/rule/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 101,
                    'status'     => 'normal',
                ),
            53 =>
                array(
                    'id'         => 54,
                    'type'       => 'file',
                    'pid'        => 12,
                    'name'       => 'auth/rule/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1497429920,
                    'updated_at' => 1497429920,
                    'weigh'      => 100,
                    'status'     => 'normal',
                ),
            54 =>
                array(
                    'id'         => 55,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => 'Addon tips',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            55 =>
                array(
                    'id'         => 56,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            56 =>
                array(
                    'id'         => 57,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            57 =>
                array(
                    'id'         => 58,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/del',
                    'title'      => 'Delete',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            58 =>
                array(
                    'id'         => 59,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/local',
                    'title'      => 'Local install',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            59 =>
                array(
                    'id'         => 60,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/state',
                    'title'      => 'Update state',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            60 =>
                array(
                    'id'         => 61,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/install',
                    'title'      => 'Install',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            61 =>
                array(
                    'id'         => 62,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/uninstall',
                    'title'      => 'Uninstall',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            62 =>
                array(
                    'id'         => 63,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/config',
                    'title'      => 'Setting',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            63 =>
                array(
                    'id'         => 64,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/refresh',
                    'title'      => 'Refresh',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            64 =>
                array(
                    'id'         => 65,
                    'type'       => 'file',
                    'pid'        => 4,
                    'name'       => 'addon/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1502035509,
                    'updated_at' => 1502035509,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            65 =>
                array(
                    'id'         => 66,
                    'type'       => 'file',
                    'pid'        => 0,
                    'name'       => 'user',
                    'title'      => 'User',
                    'icon'       => 'fa fa-list',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            66 =>
                array(
                    'id'         => 67,
                    'type'       => 'file',
                    'pid'        => 66,
                    'name'       => 'user/user',
                    'title'      => 'User',
                    'icon'       => 'fa fa-user',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            67 =>
                array(
                    'id'         => 68,
                    'type'       => 'file',
                    'pid'        => 67,
                    'name'       => 'user/user/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            68 =>
                array(
                    'id'         => 69,
                    'type'       => 'file',
                    'pid'        => 67,
                    'name'       => 'user/user/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            69 =>
                array(
                    'id'         => 70,
                    'type'       => 'file',
                    'pid'        => 67,
                    'name'       => 'user/user/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            70 =>
                array(
                    'id'         => 71,
                    'type'       => 'file',
                    'pid'        => 67,
                    'name'       => 'user/user/del',
                    'title'      => 'Del',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            71 =>
                array(
                    'id'         => 72,
                    'type'       => 'file',
                    'pid'        => 67,
                    'name'       => 'user/user/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            72 =>
                array(
                    'id'         => 73,
                    'type'       => 'file',
                    'pid'        => 66,
                    'name'       => 'user/group',
                    'title'      => 'User group',
                    'icon'       => 'fa fa-users',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            73 =>
                array(
                    'id'         => 74,
                    'type'       => 'file',
                    'pid'        => 73,
                    'name'       => 'user/group/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            74 =>
                array(
                    'id'         => 75,
                    'type'       => 'file',
                    'pid'        => 73,
                    'name'       => 'user/group/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            75 =>
                array(
                    'id'         => 76,
                    'type'       => 'file',
                    'pid'        => 73,
                    'name'       => 'user/group/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            76 =>
                array(
                    'id'         => 77,
                    'type'       => 'file',
                    'pid'        => 73,
                    'name'       => 'user/group/del',
                    'title'      => 'Del',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            77 =>
                array(
                    'id'         => 78,
                    'type'       => 'file',
                    'pid'        => 73,
                    'name'       => 'user/group/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            78 =>
                array(
                    'id'         => 79,
                    'type'       => 'file',
                    'pid'        => 66,
                    'name'       => 'user/rule',
                    'title'      => 'User rule',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            79 =>
                array(
                    'id'         => 80,
                    'type'       => 'file',
                    'pid'        => 79,
                    'name'       => 'user/rule/index',
                    'title'      => 'View',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            80 =>
                array(
                    'id'         => 81,
                    'type'       => 'file',
                    'pid'        => 79,
                    'name'       => 'user/rule/del',
                    'title'      => 'Del',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            81 =>
                array(
                    'id'         => 82,
                    'type'       => 'file',
                    'pid'        => 79,
                    'name'       => 'user/rule/add',
                    'title'      => 'Add',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            82 =>
                array(
                    'id'         => 83,
                    'type'       => 'file',
                    'pid'        => 79,
                    'name'       => 'user/rule/edit',
                    'title'      => 'Edit',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
            83 =>
                array(
                    'id'         => 84,
                    'type'       => 'file',
                    'pid'        => 79,
                    'name'       => 'user/rule/multi',
                    'title'      => 'Multi',
                    'icon'       => 'fa fa-circle-o',
                    'condition'  => '',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516374729,
                    'updated_at' => 1516374729,
                    'weigh'      => 0,
                    'status'     => 'normal',
                ),
        ),
    'category'          =>
        array(
            0  =>
                array(
                    'id'          => 1,
                    'pid'         => 0,
                    'type'        => 'page',
                    'name'        => '官方新闻',
                    'nickname'    => 'news',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'news',
                    'created_at'  => 1495262190,
                    'updated_at'  => 1495262190,
                    'weigh'       => 1,
                    'status'      => 'normal',
                ),
            1  =>
                array(
                    'id'          => 2,
                    'pid'         => 0,
                    'type'        => 'page',
                    'name'        => '移动应用',
                    'nickname'    => 'mobileapp',
                    'flag'        => 'hot',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'mobileapp',
                    'created_at'  => 1495262244,
                    'updated_at'  => 1495262244,
                    'weigh'       => 2,
                    'status'      => 'normal',
                ),
            2  =>
                array(
                    'id'          => 3,
                    'pid'         => 2,
                    'type'        => 'page',
                    'name'        => '微信公众号',
                    'nickname'    => 'wechatpublic',
                    'flag'        => 'index',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'wechatpublic',
                    'created_at'  => 1495262288,
                    'updated_at'  => 1495262288,
                    'weigh'       => 3,
                    'status'      => 'normal',
                ),
            3  =>
                array(
                    'id'          => 4,
                    'pid'         => 2,
                    'type'        => 'page',
                    'name'        => 'Android开发',
                    'nickname'    => 'android',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'android',
                    'created_at'  => 1495262317,
                    'updated_at'  => 1495262317,
                    'weigh'       => 4,
                    'status'      => 'normal',
                ),
            4  =>
                array(
                    'id'          => 5,
                    'pid'         => 0,
                    'type'        => 'page',
                    'name'        => '软件产品',
                    'nickname'    => 'software',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'software',
                    'created_at'  => 1495262336,
                    'updated_at'  => 1499681850,
                    'weigh'       => 5,
                    'status'      => 'normal',
                ),
            5  =>
                array(
                    'id'          => 6,
                    'pid'         => 5,
                    'type'        => 'page',
                    'name'        => '网站建站',
                    'nickname'    => 'website',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'website',
                    'created_at'  => 1495262357,
                    'updated_at'  => 1495262357,
                    'weigh'       => 6,
                    'status'      => 'normal',
                ),
            6  =>
                array(
                    'id'          => 7,
                    'pid'         => 5,
                    'type'        => 'page',
                    'name'        => '企业管理软件',
                    'nickname'    => 'company',
                    'flag'        => 'index',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'company',
                    'created_at'  => 1495262391,
                    'updated_at'  => 1495262391,
                    'weigh'       => 7,
                    'status'      => 'normal',
                ),
            7  =>
                array(
                    'id'          => 8,
                    'pid'         => 6,
                    'type'        => 'page',
                    'name'        => 'PC端',
                    'nickname'    => 'website-pc',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'website-pc',
                    'created_at'  => 1495262424,
                    'updated_at'  => 1495262424,
                    'weigh'       => 8,
                    'status'      => 'normal',
                ),
            8  =>
                array(
                    'id'          => 9,
                    'pid'         => 6,
                    'type'        => 'page',
                    'name'        => '移动端',
                    'nickname'    => 'website-mobile',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'website-mobile',
                    'created_at'  => 1495262456,
                    'updated_at'  => 1495262456,
                    'weigh'       => 9,
                    'status'      => 'normal',
                ),
            9  =>
                array(
                    'id'          => 10,
                    'pid'         => 7,
                    'type'        => 'page',
                    'name'        => 'CRM系统 ',
                    'nickname'    => 'company-crm',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'company-crm',
                    'created_at'  => 1495262487,
                    'updated_at'  => 1495262487,
                    'weigh'       => 10,
                    'status'      => 'normal',
                ),
            10 =>
                array(
                    'id'          => 11,
                    'pid'         => 7,
                    'type'        => 'page',
                    'name'        => 'SASS平台软件',
                    'nickname'    => 'company-sass',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'company-sass',
                    'created_at'  => 1495262515,
                    'updated_at'  => 1495262515,
                    'weigh'       => 11,
                    'status'      => 'normal',
                ),
            11 =>
                array(
                    'id'          => 12,
                    'pid'         => 0,
                    'type'        => 'test',
                    'name'        => '测试1',
                    'nickname'    => 'test1',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'test1',
                    'created_at'  => 1497015727,
                    'updated_at'  => 1497015727,
                    'weigh'       => 12,
                    'status'      => 'normal',
                ),
            12 =>
                array(
                    'id'          => 13,
                    'pid'         => 0,
                    'type'        => 'test',
                    'name'        => '测试2',
                    'nickname'    => 'test2',
                    'flag'        => 'recommend',
                    'image'       => '/assets/img/qrcode.png',
                    'keywords'    => '',
                    'description' => '',
                    'diyname'     => 'test2',
                    'created_at'  => 1497015738,
                    'updated_at'  => 1497015738,
                    'weigh'       => 13,
                    'status'      => 'normal',
                ),
        ),
    'config'            =>
        array(
            0  =>
                array(
                    'id'      => 1,
                    'name'    => 'name',
                    'group'   => 'basic',
                    'title'   => 'Site name',
                    'tip'     => '请填写站点名称',
                    'type'    => 'string',
                    'value'   => 'dd',
                    'content' => '',
                    'rule'    => 'required',
                    'extend'  => '',
                ),
            1  =>
                array(
                    'id'      => 2,
                    'name'    => 'beian',
                    'group'   => 'basic',
                    'title'   => 'Beian',
                    'tip'     => '粤ICP备15054802号-4',
                    'type'    => 'string',
                    'value'   => '',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            2  =>
                array(
                    'id'      => 3,
                    'name'    => 'cdnurl',
                    'group'   => 'basic',
                    'title'   => 'Cdn url',
                    'tip'     => '如果静态资源使用第三方云储存请配置该值',
                    'type'    => 'string',
                    'value'   => '',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            3  =>
                array(
                    'id'      => 4,
                    'name'    => 'version',
                    'group'   => 'basic',
                    'title'   => 'Version',
                    'tip'     => '如果静态资源有变动请重新配置该值',
                    'type'    => 'string',
                    'value'   => '1.0.1.2',
                    'content' => '',
                    'rule'    => 'required',
                    'extend'  => '',
                ),
            4  =>
                array(
                    'id'      => 5,
                    'name'    => 'timezone',
                    'group'   => 'basic',
                    'title'   => 'Timezone',
                    'tip'     => '',
                    'type'    => 'string',
                    'value'   => 'Asia/Shanghai',
                    'content' => '',
                    'rule'    => 'required',
                    'extend'  => '',
                ),
            5  =>
                array(
                    'id'      => 6,
                    'name'    => 'forbiddenip',
                    'group'   => 'basic',
                    'title'   => 'Forbidden ip',
                    'tip'     => '一行一条记录',
                    'type'    => 'text',
                    'value'   => '',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            6  =>
                array(
                    'id'      => 7,
                    'name'    => 'languages',
                    'group'   => 'basic',
                    'title'   => 'Languages',
                    'tip'     => '',
                    'type'    => 'array',
                    'value'   => '{"backend":"zh-cn","frontend":"zh-cn"}',
                    'content' => '',
                    'rule'    => 'required',
                    'extend'  => '',
                ),
            7  =>
                array(
                    'id'      => 8,
                    'name'    => 'fixedpage',
                    'group'   => 'basic',
                    'title'   => 'Fixed page',
                    'tip'     => '请尽量输入左侧菜单栏存在的链接',
                    'type'    => 'string',
                    'value'   => 'dashboard',
                    'content' => '',
                    'rule'    => 'required',
                    'extend'  => '',
                ),
            8  =>
                array(
                    'id'      => 9,
                    'name'    => 'categorytype',
                    'group'   => 'dictionary',
                    'title'   => 'Category type',
                    'tip'     => '',
                    'type'    => 'array',
                    'value'   => '{"default":"Default","page":"Page","article":"Article","test":"Test"}',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            9  =>
                array(
                    'id'      => 10,
                    'name'    => 'configgroup',
                    'group'   => 'dictionary',
                    'title'   => 'Config group',
                    'tip'     => '',
                    'type'    => 'array',
                    'value'   => '{"basic":"Basic","email":"Email","dictionary":"Dictionary","user":"User","example":"Example"}',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            10 =>
                array(
                    'id'      => 11,
                    'name'    => 'mail_type',
                    'group'   => 'email',
                    'title'   => 'Mail type',
                    'tip'     => '选择邮件发送方式',
                    'type'    => 'select',
                    'value'   => '1',
                    'content' => '["Please select","SMTP","Mail"]',
                    'rule'    => '',
                    'extend'  => '',
                ),
            11 =>
                array(
                    'id'      => 12,
                    'name'    => 'mail_smtp_host',
                    'group'   => 'email',
                    'title'   => 'Mail smtp host',
                    'tip'     => '错误的配置发送邮件会导致服务器超时',
                    'type'    => 'string',
                    'value'   => 'smtp.qq.com',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            12 =>
                array(
                    'id'      => 13,
                    'name'    => 'mail_smtp_port',
                    'group'   => 'email',
                    'title'   => 'Mail smtp port',
                    'tip'     => '(不加密默认25,SSL默认465,TLS默认587)',
                    'type'    => 'string',
                    'value'   => '465',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            13 =>
                array(
                    'id'      => 14,
                    'name'    => 'mail_smtp_user',
                    'group'   => 'email',
                    'title'   => 'Mail smtp user',
                    'tip'     => '（填写完整用户名）',
                    'type'    => 'string',
                    'value'   => '10000',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            14 =>
                array(
                    'id'      => 15,
                    'name'    => 'mail_smtp_pass',
                    'group'   => 'email',
                    'title'   => 'Mail smtp password',
                    'tip'     => '（填写您的密码）',
                    'type'    => 'string',
                    'value'   => 'password',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            15 =>
                array(
                    'id'      => 16,
                    'name'    => 'mail_verify_type',
                    'group'   => 'email',
                    'title'   => 'Mail vertify type',
                    'tip'     => '（SMTP验证方式[推荐SSL]）',
                    'type'    => 'select',
                    'value'   => '2',
                    'content' => '["None","TLS","SSL"]',
                    'rule'    => '',
                    'extend'  => '',
                ),
            16 =>
                array(
                    'id'      => 17,
                    'name'    => 'mail_from',
                    'group'   => 'email',
                    'title'   => 'Mail from',
                    'tip'     => '',
                    'type'    => 'string',
                    'value'   => '10000@qq.com',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            17 =>
                array(
                    'id'      => 18,
                    'name'    => 'date',
                    'group'   => 'basic',
                    'title'   => '日期',
                    'tip'     => '',
                    'type'    => 'date',
                    'value'   => '',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            18 =>
                array(
                    'id'      => 19,
                    'name'    => 'string',
                    'group'   => 'basic',
                    'title'   => '字符',
                    'tip'     => '',
                    'type'    => 'switch',
                    'value'   => '',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            19 =>
                array(
                    'id'      => 20,
                    'name'    => 'uploadurl',
                    'group'   => 'upload',
                    'title'   => '上传地址',
                    'tip'     => '默认是本地上传',
                    'type'    => 'string',
                    'value'   => 'ajax/upload',
                    'content' => '',
                    'rule'    => 'require',
                    'extend'  => '',
                ),
            20 =>
                array(
                    'id'      => 21,
                    'name'    => 'cdnurl',
                    'group'   => 'upload',
                    'title'   => 'Cdn url',
                    'tip'     => '如果静态资源使用第三方云储存请配置该值',
                    'type'    => 'string',
                    'value'   => '',
                    'content' => '',
                    'rule'    => '',
                    'extend'  => '',
                ),
            21 =>
                array(
                    'id'      => 26,
                    'name'    => 'savekey',
                    'group'   => 'upload',
                    'title'   => '文件保存格式',
                    'tip'     => '',
                    'type'    => 'string',
                    'value'   => '/uploads/{year}{mon}{day}/{filemd5}{.suffix}',
                    'content' => ' ',
                    'rule'    => 'require',
                    'extend'  => '',
                ),
            22 =>
                array(
                    'id'      => 27,
                    'name'    => 'maxsize',
                    'group'   => 'upload',
                    'title'   => '可上传文件大小',
                    'tip'     => '',
                    'type'    => 'string',
                    'value'   => '10mb',
                    'content' => ' ',
                    'rule'    => 'require',
                    'extend'  => '',
                ),
            23 =>
                array(
                    'id'      => 28,
                    'name'    => 'mimetype',
                    'group'   => 'upload',
                    'title'   => '可上传文件类型',
                    'tip'     => '',
                    'type'    => 'string',
                    'value'   => 'jpg,png,bmp,jpeg,gif,zip,rar,xls,xlsx',
                    'content' => ' ',
                    'rule'    => 'require',
                    'extend'  => '',
                ),
            24 =>
                array(
                    'id'      => 29,
                    'name'    => 'multiple',
                    'group'   => 'upload',
                    'title'   => '是否支持批量上传',
                    'tip'     => '',
                    'type'    => 'radio',
                    'value'   => 'false',
                    'content' => ' {"true":"是","false":"否"}',
                    'rule'    => '',
                    'extend'  => '',
                ),
            25 =>
                array(
                    'id'      => 30,
                    'name'    => 'keeptime',
                    'group'   => 'basic',
                    'title'   => 'Keep Time',
                    'tip'     => 's',
                    'type'    => 'number',
                    'value'   => '1800',
                    'content' => '',
                    'rule'    => 'require',
                    'extend'  => '',
                ),
        ),
    'test'              =>
        array(
            0 =>
                array(
                    'id'           => 1,
                    'admin_id'     => 0,
                    'category_id'  => 12,
                    'category_ids' => '12,13',
                    'week'         => 'monday',
                    'flag'         => 'hot,index',
                    'genderdata'   => 'male',
                    'hobbydata'    => 'music,reading',
                    'title'        => '我是一篇测试文章',
                    'content'      => '<p>我是测试内容</p>',
                    'image'        => '/assets/img/avatar.png',
                    'images'       => '/assets/img/avatar.png,/assets/img/qrcode.png',
                    'attachfile'   => '/assets/img/avatar.png',
                    'keywords'     => '关键字',
                    'description'  => '描述',
                    'city'         => '广西壮族自治区/百色市/平果县',
                    'price'        => 0.0,
                    'views'        => 0,
                    'startdate'    => '2017-07-10',
                    'activitytime' => '2017-07-10 18:24:45',
                    'year'         => 2017,
                    'times'        => '18:24:45',
                    'refreshtime'  => 1499682285,
                    'created_at'   => 1499682526,
                    'updated_at'   => 1499682526,
                    'weigh'        => 0,
                    'switch'       => 1,
                    'status'       => 'normal',
                    'state'        => '1',
                ),
        ),
    'user'              =>
        array(
            0 =>
                array(
                    'id'             => 1,
                    'group_id'       => 1,
                    'username'       => 'admin',
                    'nickname'       => 'admin',
                    'password'       => 'c13f62012fd6a8fdf06b3452a94430e5',
                    'salt'           => 'rpR6Bv',
                    'email'          => 'admin@163.com',
                    'mobile'         => '13888888888',
                    'avatar'         => '/assets/img/avatar.png',
                    'level'          => 0,
                    'gender'         => 0,
                    'birthday'       => '2017-04-15',
                    'bio'            => '',
                    'money'          => '0.00',
                    'score'          => 0,
                    'successions'    => 1,
                    'maxsuccessions' => 1,
                    'prevtime'       => 1516170492,
                    'logintime'      => 1516171614,
                    'loginip'        => '127.0.0.1',
                    'loginfailure'   => 0,
                    'joinip'         => '127.0.0.1',
                    'jointime'       => 1491461418,
                    'created_at'     => 0,
                    'updated_at'     => 1516171614,
                    'token'          => '',
                    'status'         => 'normal',
                    'verification'   => '',
                ),
        ),
    'user_group'        =>
        array(
            0 =>
                array(
                    'id'         => 1,
                    'name'       => '默认组',
                    'rules'      => '1,2,3,4,5,6,7,8,9,10,11,12',
                    'created_at' => 1515386468,
                    'updated_at' => 1516168298,
                    'status'     => 'normal',
                ),
        ),
    'user_rule'         =>
        array(
            0  =>
                array(
                    'id'         => 1,
                    'pid'        => 0,
                    'name'       => 'index',
                    'title'      => '前台',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1516168079,
                    'updated_at' => 1516168079,
                    'weigh'      => 1,
                    'status'     => 'normal',
                ),
            1  =>
                array(
                    'id'         => 2,
                    'pid'        => 0,
                    'name'       => 'api',
                    'title'      => 'API接口',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1516168062,
                    'updated_at' => 1516168062,
                    'weigh'      => 2,
                    'status'     => 'normal',
                ),
            2  =>
                array(
                    'id'         => 3,
                    'pid'        => 1,
                    'name'       => 'user',
                    'title'      => '会员模块',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1515386221,
                    'updated_at' => 1516168103,
                    'weigh'      => 12,
                    'status'     => 'normal',
                ),
            3  =>
                array(
                    'id'         => 4,
                    'pid'        => 2,
                    'name'       => 'user',
                    'title'      => '会员模块',
                    'remark'     => '',
                    'ismenu'     => 1,
                    'created_at' => 1515386221,
                    'updated_at' => 1516168092,
                    'weigh'      => 11,
                    'status'     => 'normal',
                ),
            4  =>
                array(
                    'id'         => 5,
                    'pid'        => 3,
                    'name'       => 'index/user/login',
                    'title'      => '登录',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1515386247,
                    'updated_at' => 1515386247,
                    'weigh'      => 5,
                    'status'     => 'normal',
                ),
            5  =>
                array(
                    'id'         => 6,
                    'pid'        => 3,
                    'name'       => 'index/user/register',
                    'title'      => '注册',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1515386262,
                    'updated_at' => 1516015236,
                    'weigh'      => 7,
                    'status'     => 'normal',
                ),
            6  =>
                array(
                    'id'         => 7,
                    'pid'        => 3,
                    'name'       => 'index/user/index',
                    'title'      => '会员中心',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516015012,
                    'updated_at' => 1516015012,
                    'weigh'      => 9,
                    'status'     => 'normal',
                ),
            7  =>
                array(
                    'id'         => 8,
                    'pid'        => 3,
                    'name'       => 'index/user/profile',
                    'title'      => '个人资料',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516015012,
                    'updated_at' => 1516015012,
                    'weigh'      => 4,
                    'status'     => 'normal',
                ),
            8  =>
                array(
                    'id'         => 9,
                    'pid'        => 4,
                    'name'       => 'api/user/login',
                    'title'      => '登录',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1515386247,
                    'updated_at' => 1515386247,
                    'weigh'      => 6,
                    'status'     => 'normal',
                ),
            9  =>
                array(
                    'id'         => 10,
                    'pid'        => 4,
                    'name'       => 'api/user/register',
                    'title'      => '注册',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1515386262,
                    'updated_at' => 1516015236,
                    'weigh'      => 8,
                    'status'     => 'normal',
                ),
            10 =>
                array(
                    'id'         => 11,
                    'pid'        => 4,
                    'name'       => 'api/user/index',
                    'title'      => '会员中心',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516015012,
                    'updated_at' => 1516015012,
                    'weigh'      => 10,
                    'status'     => 'normal',
                ),
            11 =>
                array(
                    'id'         => 12,
                    'pid'        => 4,
                    'name'       => 'api/user/profile',
                    'title'      => '个人资料',
                    'remark'     => '',
                    'ismenu'     => 0,
                    'created_at' => 1516015012,
                    'updated_at' => 1516015012,
                    'weigh'      => 3,
                    'status'     => 'normal',
                ),
        ),
    'version'           =>
        array(
            0 =>
                array(
                    'id'          => 1,
                    'oldversion'  => '1.1.1,2',
                    'newversion'  => '1.2.1',
                    'packagesize' => '20M',
                    'content'     => '更新内容',
                    'downloadurl' => 'https://www.fastadmin.net/download.html',
                    'enforce'     => 1,
                    'created_at'  => 1520425318,
                    'updated_at'  => 0,
                    'weigh'       => 0,
                    'status'      => 'normal',
                ),
        ),
);